# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitmarkdown < Formula
  desc "CLI tool to convert contents of a folder to LLM-ingestable markdown file."
  homepage "https://github.com/pranjalya/gitmarkdown"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Pranjalya/gitmarkdown/releases/download/v1.0.0/gitmarkdown_1.0.0_darwin_amd64.tar.gz"
      sha256 "5a7722b400fadc2fa6f66baa2ed2e3f3db0bfcda160731dab8f8c46c0bf8b545"

      def install
        bin.install "gitmarkdown"
      end
    end
    on_arm do
      url "https://github.com/Pranjalya/gitmarkdown/releases/download/v1.0.0/gitmarkdown_1.0.0_darwin_arm64.tar.gz"
      sha256 "a7d2c3ee52eed0480faa11e15fd6b9a7f2ac98ae78dd3c541526b0a8474dc3d4"

      def install
        bin.install "gitmarkdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Pranjalya/gitmarkdown/releases/download/v1.0.0/gitmarkdown_1.0.0_linux_amd64.tar.gz"
        sha256 "5321280e7267585292800847304f83f121f661d145b92d730329b48785206ec7"

        def install
          bin.install "gitmarkdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Pranjalya/gitmarkdown/releases/download/v1.0.0/gitmarkdown_1.0.0_linux_arm64.tar.gz"
        sha256 "3c1651709409dff5e3ad36471ed12bcd2793e0dcdbc4c3883b6abadfdffc62d0"

        def install
          bin.install "gitmarkdown"
        end
      end
    end
  end
end
