# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subgit < Formula
  desc "Downloads a subdirectory from a github repository"
  homepage "https://github.com/pranjalya/subgit"
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/Pranjalya/subgit/releases/download/v0.7.0/subgit_0.7.0_darwin_amd64.tar.gz"
      sha256 "9e82b216cb8566a1417067f3f74a7f61a00ce0f9286a2e9b79939ba621488ad9"

      def install
        bin.install "subgit"
      end
    end
    on_arm do
      url "https://github.com/Pranjalya/subgit/releases/download/v0.7.0/subgit_0.7.0_darwin_arm64.tar.gz"
      sha256 "f829debdc7ac3b5765c08e3e738e0ea753e75109b5bd5dac6afe6b178c47c551"

      def install
        bin.install "subgit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Pranjalya/subgit/releases/download/v0.7.0/subgit_0.7.0_linux_amd64.tar.gz"
        sha256 "6e0e1adcec4e7fdf8bffe85a1ac3ec544c76f6d47ff25c8197da80d935fb7d5a"

        def install
          bin.install "subgit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Pranjalya/subgit/releases/download/v0.7.0/subgit_0.7.0_linux_arm64.tar.gz"
        sha256 "704f9f6b1505ca2e6b6c705ea528ace76f9fd7ad81b7242dc478c6a98f9796aa"

        def install
          bin.install "subgit"
        end
      end
    end
  end
end
